version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT}:4000"
    environment:
      DATABASE_URL: "mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@mysql:3306/${DATABASE_NAME}"
      # Add other env vars as needed
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/node_modules/.prisma
    command: >
      sh -c "
      echo 'Waiting for database to be ready...';
      until npx prisma migrate dev --name init; do
        echo 'Migration failed, retrying in 5 seconds...';
        sleep 5;
      done;
      echo 'Migrations applied successfully!';
      npm dev;
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql-data: